### ISSUE TITLE
Absolute file path for .vstags file

### ISSUE THREAD

**Issue by kak-tus** [henriiik/vscode-perl#1]
Hello,

Plugin creates .vstags in each project dir.

Is it able to disable file creation?
Or to use absolute file path for all projects (it's not good idea)?
Or use absolute path + filename genereted from project dir name?

**Comment by henriiik** [comment]
Hello!

Why do you want to disable the file creation? :)

**Comment by kak-tus** [comment]
I have near 800 git repositories with perl code. And when I edit files from one of this repositories - plugin creates file in this repo. So I need to add .vstags to each of this 800 .gitignore file and this is not excellent solution.

**Comment by henriiik** [comment]
You can create a global .gitignore file, and you have have to add `.vstags` once. :)

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by kak-tus** [comment]
Hm, It's idea. Thank you.
