### ISSUE TITLE
Is it possible to get the definitions of all workspace folders?

### ISSUE THREAD

**Issue by fernandolobo** [henriiik/vscode-perl#10]
I have a workspace with five folders in the root, the tool creates the .vstags file only in the first folder.
Is it possible to get the functions definitions of all workspace folders?

**Comment by henriiik** [comment]
hello!

I have begun looking into this, but it will probably take a while. :)

**Comment by michaelherger** [comment]
Yes, please :-)

**Comment by henriiik** [comment]
Hello!

I have built a new version of the extension with support for workspaces included. You can try it out bu downloading it and installing it in vscode manually (https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

https://github.com/henriiik/vscode-perl/raw/master/vscode-perl-1.15.0.vsix

I will try it out for a week or so before releasing it.

**Comment by michaelherger** [comment]
Cool! The first minute of testing is looking good! Will know more in a few days.

**Comment by fernandolobo** [comment]
It works. 
Good job! Thank you!
