### ISSUE TITLE
Cursor position changed ot EOF after formatting perl

### ISSUE THREAD

**Issue by dermoench42** [henriiik/vscode-perl#17]
Issue Type: <b>Bug</b>

Create Perl script or module, and format it. Then try the arrow keys to go up and down - the curser is at the End of the File.
Because this only apears on perl files I assume it is a Perl Extension issue.

Extension version: 1.14.4
VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.14.32-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 x 3729)|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (0.15GB free)|
|Process Argv|/home/peters/bin/VSCode-linux-x64/code|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by henriiik** [comment]
this should be fixed by vscode in the latest 1.12.2 https://github.com/Microsoft/vscode/issues/47382
