### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by willt** [henriiik/vscode-perl#3]
When I try formatting something I get "Error: write EPIPE" in the output window.
I'm on Windows 10, perltidy is installed and runable from terminal. 
Any idea what could be wrong ?

**Comment by henriiik** [comment]
Hello!

Is it runnable if you just start a "plain" cmd.exe?

You could try to add the `perl.perltidy` setting and set it to the path to perltidy.

**Comment by henriiik** [comment]
closing this due to lack of response.
